# Generated by Django 3.0.2 on 2021-12-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image',
            field=models.ImageField(default='bus_logo.png', upload_to='business_pp'),
        ),
    ]
