# Generated by Django 3.0.2 on 2022-05-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211216_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
