# Generated by Django 3.0.2 on 2021-12-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='image',
            field=models.ImageField(default='host_logo.png', upload_to='hospital_pp'),
        ),
    ]
